version: '3'
services:
  neo4j:
    container_name: ai-insights-neo4j
    restart: unless-stopped
    image: neo4j:5.21-community-bullseye
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/development
      NEO4JLABS_PLUGINS: '["apoc"]'

